name: Golang build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0' # The Go version to download (if necessary) and use.

      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      # Run build of the application
      - name: Run build
        run: go build -v ./...
        
      - name: Test
        run: go test -v ./...

      # Run vet on the code
      - name: Run vet
        run: |
          go vet -v ./...

